# 
# https://blog.csdn.net/qq_28550263/article/details/131182040
# name	表示项目名称。
# description	表示项目描述。
# version	表示项目版本。
# author/authors	表示项目作者。
# homepage	项目的主页。
# repository	项目的代码仓库。
# issue_tracker	项目的问题跟踪器。
# documentation	项目的文档。
# executables	项目的可执行文件。

name: flutter_shudu_one
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1



environment:
  sdk: '>=3.3.2 <4.0.0'

# dependencies	项目的直接依赖。
# dev_dependencies	项目的开发依赖。
# dependency_overrides	覆盖依赖。
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '^0.18.1'
  sudoku_dart: '^1.1.0'
  logger: "^2.2.0"
  sprintf: "^7.0.0"
  scoped_model: "^2.0.0"
#  modal_bottom_sheet: "^2.1.2"
  modal_bottom_sheet:
    git:
      url: https://github.com/saltedpotatos/modal_bottom_sheet.git
      path: modal_bottom_sheet
      ref: e7e630e10b27ccab12da27acada9d47a13d79e9a
  hive: "^2.2.3"
  hive_flutter: "^1.1.0"

  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  just_audio: ^0.9.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0

# assets	项目的资源文件列表。
# fonts	项目的字体配置。
# generate	设置是否为 l10n.yaml 文件中定义的本地化资源生成 Dart 文件。
# plugin	配置 Flutter 插件的平台特定实现。
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/image/
    - assets/audio/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
